// <auto-generated />
namespace ToDoList.Auth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class updatedToDoListModelwithpublicprop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedToDoListModelwithpublicprop));
        
        string IMigrationMetadata.Id
        {
            get { return "201703141241213_updated ToDoListModel with public prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
